name: Run Bash Script

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Bash script
        run: |
          chmod +x ./script.sh  # Make the script executable
          ./script.sh            # Execute the script
    